calci_client.exe : calci_client.c
	gcc -o calci_client.exe calci_client.c -I../Include
calci_server.exe : calci_server.c
	gcc -o calci_server.exe calci_server.c -loperation -L../Library -I../Include
relay_agent.exe : relay_agent.c
	gcc -o relay_agent.exe relay_agent.c -I../Include
